services:
  frontend:
    build: .
    container_name: quizhive_frontend
    env_file: .env
    user: node
    ports:
      - '$PORT:8081'
#    volumes:
#      - .:/home/node/app
    restart: unless-stopped
