services:
  frontend:
    image: amiril/quizhive-front-react:latest
#    build: .
    container_name: quizhive_frontend
    env_file: .env
    user: node
    ports:
      - '$PORT:$PORT'
#    volumes:
#      - .:/home/node/app
    restart: unless-stopped
